import { useEffect, useRef, useState } from 'react';
import { NavLink, Link, Outlet, useLocation } from 'react-router-dom';
import { Activity, ArrowRight, CalendarClock, CircleCheck, FlaskConical, Gauge, History, Inbox, LayoutGrid, LogOut, Menu, PackageCheck, Route, Truck, Wifi, WifiOff, X } from 'lucide-react';
import { useAuth } from '../../../app/providers/AuthProvider';
import { ErrorPanel } from '../../../components/shared/ui';
import { useDispatcher } from './context';
import { useOverview } from './overview-context';
import { scopeName } from './Overview';
const navigation=[['/','Overview',LayoutGrid],['/orders','Orders',Inbox],['/planning','Trip Planning',Route],['/loading','Loading',PackageCheck],['/monitoring','Delivery Monitoring',Activity],['/deferrals','Deferrals',CalendarClock],['/vehicles','Vehicles',Truck],['/forecast','Capacity Forecast',Gauge],['/history','History',History],['/checks','System Checks',FlaskConical]] as const;
export function DispatcherShell(){
  const {user,logout}=useAuth(), {date,setDate,depotId,setDepotId,depots,depotError,refreshDepots}=useDispatcher(), data=useOverview();
  const {pathname}=useLocation();
  const previousPath = useRef(pathname), refresh = useRef(data.refresh);
  refresh.current = data.refresh;
  const [now,setNow]=useState(new Date()),[open,setOpen]=useState(false),[online,setOnline]=useState(navigator.onLine);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),30000);const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{clearInterval(timer);window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
  useEffect(()=>{setOpen(false);window.scrollTo(0,0);if(previousPath.current!==pathname){previousPath.current=pathname;refresh.current();}},[pathname]);
  useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLElement>('.dispatch-drawer a, .dispatch-drawer button'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);document.querySelector<HTMLElement>('.dispatch-menu-button')?.focus();};},[open]);
  const [first]=data.actions;
  const status=!online?'Offline':data.error?'Needs refresh':!data.ordersReady||!data.tripsReady?'Connecting':'Live';
  const counts:Record<string,number>={'/orders':data.waiting.length,'/monitoring':data.late.length,'/deferrals':data.repeat.length,'/loading':data.exceptions};
  const nav=<><Link to="/" className="dispatch-brand"><img src="/Blue_Simple_Delivery_Truck_Logo.png" alt=""/><span>Waypoint<small>Dispatcher</small></span></Link><nav aria-label="Dispatcher navigation">{navigation.map(([path,label,Icon])=><NavLink key={path} aria-label={label} to={path} end={path==='/'}><Icon size={20}/><span>{label}</span>{counts[path]>0&&<b className={`dispatch-nav-count ${['/monitoring','/deferrals'].includes(path)?'alert':''}`}>{counts[path]}</b>}</NavLink>)}</nav><div className="dispatch-next-up">{first?<><span className="dispatch-next-icon"><first.icon size={19}/></span><small>Do this next</small><p>{first.title}</p><Link to={first.to}>{first.cta}<ArrowRight size={17}/></Link></>:<><CircleCheck size={22}/><p>{data.busy?'Checking operations…':data.error?'Some data is unavailable':'All caught up'}</p></>}</div></>;
  return <div className="dispatcher-live"><a className="dispatch-skip" href="#dispatcher-main">Skip to content</a><aside className="dispatch-sidebar">{nav}</aside>
    {open&&<div className="dispatch-drawer-backdrop" onClick={()=>setOpen(false)}><aside role="dialog" aria-modal="true" aria-label="Dispatcher menu" className="dispatch-drawer" onClick={e=>e.stopPropagation()}><button autoFocus aria-label="Close menu" className="dispatch-icon-button" onClick={()=>setOpen(false)}><X/></button>{nav}</aside></div>}
    <div className="dispatch-body"><header className="dispatch-topbar"><button className="dispatch-menu-button dispatch-icon-button" aria-label="Open menu" onClick={()=>setOpen(true)}><Menu/></button><span className="dispatch-scope-pill"><b>Dispatcher</b> · {scopeName(depots,depotId)}</span><time className="dispatch-clock">{now.toLocaleDateString('en-GB',{timeZone:'Asia/Colombo',weekday:'long',day:'numeric',month:'long',year:'numeric'})} · <b>{now.toLocaleTimeString('en-US',{timeZone:'Asia/Colombo',hour:'2-digit',minute:'2-digit'})}</b> Colombo</time><div className="dispatch-account"><button onClick={data.refresh} className={`dispatch-connection ${status==='Live'?'':'warning'}`} title="Refresh live data">{status==='Live'?<Wifi size={15}/>:<WifiOff size={15}/>} {status}</button><span className="dispatch-user"><b>{user?.name}</b><small>{user?.email}</small></span><span className="dispatch-avatar">{user?.name.split(' ').map(p=>p[0]).slice(0,2).join('')}</span><button aria-label="Sign out" title="Sign out" className="dispatch-icon-button" onClick={()=>void logout()}><LogOut size={21}/></button></div></header>
    <main id="dispatcher-main" className="dispatch-content"><details className="dispatch-scope-filters" open={pathname!=='/'}><summary>Run filters · {date} · {scopeName(depots,depotId)}</summary><div className="dispatch-inline"><label>Run date<input type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><label>Depot<select aria-label="Depot" value={depotId} onChange={e=>setDepotId(e.target.value)}><option value="">All depots</option>{depots.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div></details><ErrorPanel error={depotError} retry={refreshDepots}/><Outlet/></main></div>
  </div>;
}
