import { Link } from 'react-router-dom';
import { Button, ErrorPanel, Panel, numberText } from '../../../components/shared/ui';
import { useDispatcher } from './context';
import { useOverview } from './overview-context';
import { Conflicts } from './TripDetail';
export function ForecastPage(){
  const data=useOverview(),{date}=useDispatcher();
  const waiting=data.waiting.filter(o=>(o.plannedDate??o.requestedDate)===date);
  const demand=waiting.reduce((s,o)=>({kg:s.kg+(o.planningLoad?.weightKg??o.weightKg),m3:s.m3+(o.planningLoad?.volumeM3??o.volumeM3)}),{kg:0,m3:0});
  const capacity=data.free.reduce((s,v)=>({kg:s.kg+v.weightCapKg,m3:s.m3+v.volumeCapM3}),{kg:0,m3:0});
  return <><div className="dispatch-page-title"><div><h1>Capacity Forecast</h1><p>Waiting demand and currently free vehicles for {date}.</p></div><Button variant="secondary" onClick={data.refresh}>Refresh capacity</Button></div><ErrorPanel error={data.error} retry={data.refresh}/><div className="dispatch-card-grid">{([['Weight','kg',demand.kg,capacity.kg],['Volume','m³',demand.m3,capacity.m3]] as const).map(([name,unit,needed,available])=><Panel key={name} title={name}><p className="dispatch-forecast-number">{data.ordersReady?numberText(needed):'—'} <small>{unit} waiting</small></p><p>{data.fleetReady?numberText(available):'—'} {unit} available across {data.free.length} free vehicles</p><meter aria-label={`${name} demand against capacity`} min={0} max={Math.max(available,needed,1)} value={needed}/>{needed>available&&data.fleetReady&&<p className="dispatch-error">Demand exceeds free capacity by {numberText(needed-available)} {unit}.</p>}</Panel>)}</div><Panel title="Plan the next run"><p>{waiting.length} orders need allocation on this date. This estimate compares one run per free vehicle; temperature, docking, travel windows, fuel and second-trip eligibility are checked during plan validation.</p><Link to="/planning" className="dispatch-link">Open Trip Planning →</Link></Panel></>;
}
export function ChecksPage(){const data=useOverview();return <><div className="dispatch-page-title"><div><h1>System Checks</h1><p>Live data access and offline actions requiring reconciliation.</p></div><Button variant="secondary" onClick={data.refresh}>Run checks</Button></div><ErrorPanel error={data.error} retry={data.refresh}/><Panel title="Connected services"><ul className="dispatch-health-list">{[['Orders',data.ordersReady],['Trips',data.tripsReady],['Fleet',data.fleetReady],['Loading exceptions',data.issuesReady]].map(([name,ready])=><li key={String(name)}><span>{name}</span><strong>{ready?'Data loaded':'Waiting for data'}</strong></li>)}</ul><p className="dispatch-muted">These checks confirm data access. Planning validation checks whether an individual trip can run.</p></Panel><Conflicts onChanged={data.refresh}/></>;}
