import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRightIcon, CheckIcon, RefreshCwIcon, TriangleAlertIcon } from 'lucide-react';
import { LOAD_QUEUE, LOAD_STOPS } from '../data/loader';
import { PageContainer } from '../components/ui/PageContainer';
import { PageHeader } from '../components/ui/PageHeader';
import { Card } from '../components/ui/Card';
import { Button, buttonStyles } from '../components/ui/Button';
import { TripContextBar } from '../components/loader/TripContextBar';
import { useLoader } from '../contexts/LoaderContext';

export function UpdatedStopSequence() {
  const { vehicleId = 'veh031' } = useParams();
  const load = LOAD_QUEUE.find((item) => item.vehicleId.toLowerCase() === vehicleId.toLowerCase()) ?? LOAD_QUEUE[2];
  const { reviewedPlanVehicleIds, acknowledgePlanUpdate } = useLoader();
  const reviewed = reviewedPlanVehicleIds.includes(load.vehicleId);
  const loadPath = `/loader/${load.vehicleId.toLowerCase()}`;

  return <PageContainer><PageHeader backTo={{ to: '/loader', label: 'Loading Queue' }} title="Stop Sequence Updated" subtitle="Review the latest Dispatcher change before loading this trip." /><div className="mt-6"><TripContextBar vehicleId={load.vehicleId} trip={load.trip} brand={load.brand} temperature={load.temperature} /></div>
    {!reviewed ? <section role="status" className="mt-5 overflow-hidden rounded-card border border-amber/45 bg-amber-pale shadow-card"><div className="p-5 md:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-amber text-amber-ink"><TriangleAlertIcon aria-hidden="true" className="h-5 w-5" /></span><div><p className="text-base font-semibold text-amber-ink">Loading order changed for OUT027</p><p className="mt-1 max-w-xl text-sm leading-6 text-amber-ink">Waypoint Fresh · Gampaha has moved later in {load.vehicleId}’s trip. Use the updated sequence below.</p></div></div><div className="flex items-center gap-3 self-start rounded-2xl border border-amber/35 bg-surface p-3 shadow-card"><span className="min-w-[66px] text-center"><span className="block text-[11px] font-semibold tracking-wide text-subtle">WAS</span><span className="mt-1 inline-grid h-9 min-w-[66px] place-items-center rounded-full bg-canvas px-3 text-sm font-semibold tabular-nums text-ink">Stop 2</span></span><ArrowRightIcon aria-hidden="true" className="h-5 w-5 shrink-0 text-amber-ink" /><span className="min-w-[66px] text-center"><span className="block text-[11px] font-semibold tracking-wide text-amber-ink">NOW</span><span className="mt-1 inline-grid h-9 min-w-[66px] place-items-center rounded-full bg-amber px-3 text-sm font-semibold tabular-nums text-amber-ink">Stop 4</span></span></div></div><div className="mt-5 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Link to={loadPath} className={buttonStyles('secondary', 'md')}>Continue loading</Link><Button size="md" onClick={() => acknowledgePlanUpdate(load.vehicleId)}><RefreshCwIcon aria-hidden="true" className="h-4 w-4" />Review updated sequence</Button></div></div></section> : <div role="status" className="mt-5 flex flex-col gap-3 rounded-card border border-brand/20 bg-brand-pale p-5 shadow-card sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-forest">Updated sequence reviewed</p><p className="mt-1 text-sm text-forest/75">The latest Dispatcher plan is now active for {load.vehicleId}.</p></div><Link to={loadPath} className={buttonStyles('primary', 'md')}>Continue loading</Link></div>}
    <section className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_310px] lg:items-start"><Card className="p-5 md:p-7"><div className="border-b border-line pb-5"><h2 className="text-xl font-semibold tracking-tight text-ink">Updated unloading order</h2><p className="mt-1 text-sm leading-6 text-subtle">The sequence below is now the latest digital plan for {load.vehicleId}.</p></div><ol className="mt-6">{LOAD_STOPS.map((stop, index) => <li key={stop.number} className="relative flex gap-4 pb-6 last:pb-0"><span aria-hidden="true" className="relative z-10 grid h-11 w-11 shrink-0 place-items-center rounded-full bg-forest text-base font-semibold text-white shadow-card">{stop.number}</span>{index < LOAD_STOPS.length - 1 && <span aria-hidden="true" className="absolute left-[21px] top-11 h-[calc(100%-20px)] w-0.5 bg-brand-mint/75" />}<div className="min-w-0 flex-1 pb-6 last:pb-0"><p className="text-xs font-semibold tracking-wide text-subtle">STOP {stop.number}</p><h3 className="mt-1 text-xl font-semibold tracking-tight text-ink">{stop.outletId}</h3><p className="mt-1 text-sm text-subtle">{stop.outletName} · {stop.location}</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-canvas px-3 py-1.5 text-xs font-semibold text-ink">{stop.orderIds.join(' · ')}</span><span className="rounded-full bg-canvas px-3 py-1.5 text-xs font-semibold text-subtle">{stop.conditions}</span></div></div></li>)}</ol></Card><aside className="rounded-card bg-forest p-6 text-white shadow-pop"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/15 ring-1 ring-white/20"><CheckIcon aria-hidden="true" className="h-5 w-5" strokeWidth={3} /></span><h2 className="mt-5 text-xl font-semibold tracking-tight">Latest plan in view</h2><p className="mt-2 text-sm leading-6 text-white/75">This Dispatcher change is now the active loading sequence for {load.vehicleId}.</p><Link to={loadPath} className={`${buttonStyles('secondary', 'md', true)} mt-6 !border-white/25 !bg-white/10 !text-white hover:!bg-white/20`}>Open vehicle load</Link></aside></section>
  </PageContainer>;
}